baseurl = "https://ni5arga.github.io/"
enableEmoji = true
footnotereturnlinkcontents = "↩"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-us"
theme = "hugo-classic"
title = "ni5arga"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = false
guessSyntax = true
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
noClasses = true
style = "monokai"
tabWidth = 4

[permalinks]
post = "/:slug/"

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 1
[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 2
[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 3

[[menu.feed]]
name = "GitHub"
url = "https://github.com/ni5arga"

[[menu.feed]]
name = "website"
url = "https://nisarga.me"


[params]
custom_css = ["css/theme-override.css"]
description = "a place where ni5arga dumps his thoughts"
footer = "Spread Love <3 | [Website](https://nisarga.me) | [GitHub](https://github.com/ni5arga)"
favico = "static/images/favicon.ico"
